export const adminTeamsData = [
  {
    id: "1",
    name: "Jon Brown",
    role: "Front-End Developer",
    email: "jonbrown@aegonui.com",
    status: "Active",
    warehouse: "Main Warehouse",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    role: "Back-End Developer",
    email: "sarahj@aegonui.com",
    status: "Inactive",
    warehouse: "Secondary Warehouse",
  },
  {
    id: "3",
    name: "Mike Davis",
    role: "DevOps Engineer",
    email: "miked@aegonui.com",
    status: "Pending",
    warehouse: "Main Warehouse",
  },
  {
    id: "4",
    name: "Alice Smith",
    role: "Full-Stack Developer",
    email: "alices@aegonui.com",
    status: "Active",
    warehouse: "Backup Warehouse",
  },
  {
    id: "5",
    name: "Tom Harris",
    role: "Data Scientist",
    email: "tomh@aegonui.com",
    status: "Inactive",
    warehouse: "Main Warehouse",
  },
  {
    id: "6",
    name: "Emma Wilson",
    role: "Product Manager",
    email: "emmaw@aegonui.com",
    status: "Pending",
    warehouse: "Secondary Warehouse",
  },
  {
    id: "7",
    name: "David Lee",
    role: "UX Designer",
    email: "davidl@aegonui.com",
    status: "Active",
    warehouse: "Main Warehouse",
  },
  {
    id: "8",
    name: "Olivia Clark",
    role: "HR Manager",
    email: "oliviac@aegonui.com",
    status: "Inactive",
    warehouse: "Secondary Warehouse",
  },
  {
    id: "9",
    name: "Ethan White",
    role: "Quality Assurance Engineer",
    email: "ethanw@aegonui.com",
    status: "Pending",
    warehouse: "Backup Warehouse",
  },
  {
    id: "10",
    name: "Sophia Green",
    role: "Scrum Master",
    email: "sophiag@aegonui.com",
    status: "Active",
    warehouse: "Main Warehouse",
  },
];
