export const adminTeamsData = [
  {
    id: "1",
    name: "Jon Brown",
    role: "Front-End Developer",
    email: "jonbrown@aegonui.com",
    status: "Active",
    warehouse: "Main Warehouse",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    role: "Back-End Developer",
    email: "sarahj@aegonui.com",
    status: "Inactive",
    warehouse: "Secondary Warehouse",
  },
  {
    id: "3",
    name: "Mike Davis",
    role: "DevOps Engineer",
    email: "miked@aegonui.com",
    status: "Pending",
    warehouse: "Main Warehouse",
  },
  {
    id: "4",
    name: "Alice Smith",
    role: "Full-Stack Developer",
    email: "alices@aegonui.com",
    status: "Active",
    warehouse: "Backup Warehouse",
  },
  {
    id: "5",
    name: "Tom Harris",
    role: "Data Scientist",
    email: "tomh@aegonui.com",
    status: "Inactive",
    warehouse: "Main Warehouse",
  },
  {
    id: "6",
    name: "Emma Wilson",
    role: "Product Manager",
    email: "emmaw@aegonui.com",
    status: "Pending",
    warehouse: "Secondary Warehouse",
  },
  {
    id: "1",
    name: "Jon Brown",
    role: "Front-End Developer",
    email: "jonbrown@aegonui.com",
    status: "Active",
    warehouse: "Main Warehouse",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    role: "Back-End Developer",
    email: "sarahj@aegonui.com",
    status: "Inactive",
    warehouse: "Secondary Warehouse",
  },
  {
    id: "3",
    name: "Mike Davis",
    role: "DevOps Engineer",
    email: "miked@aegonui.com",
    status: "Pending",
    warehouse: "Main Warehouse",
  },
  {
    id: "4",
    name: "Alice Smith",
    role: "Full-Stack Developer",
    email: "alices@aegonui.com",
    status: "Active",
    warehouse: "Backup Warehouse",
  },
  {
    id: "5",
    name: "Tom Harris",
    role: "Data Scientist",
    email: "tomh@aegonui.com",
    status: "Inactive",
    warehouse: "Main Warehouse",
  },
  {
    id: "6",
    name: "Emma Wilson",
    role: "Product Manager",
    email: "emmaw@aegonui.com",
    status: "Pending",
    warehouse: "Secondary Warehouse",
  },
  {
    id: "1",
    name: "Jon Brown",
    role: "Front-End Developer",
    email: "jonbrown@aegonui.com",
    status: "Active",
    warehouse: "Main Warehouse",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    role: "Back-End Developer",
    email: "sarahj@aegonui.com",
    status: "Inactive",
    warehouse: "Secondary Warehouse",
  },
  {
    id: "3",
    name: "Mike Davis",
    role: "DevOps Engineer",
    email: "miked@aegonui.com",
    status: "Pending",
    warehouse: "Main Warehouse",
  },
  {
    id: "4",
    name: "Alice Smith",
    role: "Full-Stack Developer",
    email: "alices@aegonui.com",
    status: "Active",
    warehouse: "Backup Warehouse",
  },
  {
    id: "5",
    name: "Tom Harris",
    role: "Data Scientist",
    email: "tomh@aegonui.com",
    status: "Inactive",
    warehouse: "Main Warehouse",
  },
  {
    id: "6",
    name: "Emma Wilson",
    role: "Product Manager",
    email: "emmaw@aegonui.com",
    status: "pending",
    warehouse: "Secondary Warehouse",
  },
];
